### ISSUE TITLE
PyPI package doesn't include latest changes

### ISSUE THREAD

**Issue by salotz** [jaklimoff/pytest-pointers#3]
The 0.3.0 release doesn't include the latest changes. Not sure if you meant to publish it with my changes or not but it would be nice to have a release with those features.

**Comment by jaklimoff** [comment]
OH that is strange. Thank you for notifying. I will make sure it is fixed today

**Comment by jaklimoff** [comment]
@salotz , i have made new release with your changes. Also it automatically has been updated in pypi. Please have a look and confirm if everything is there.

**Comment by salotz** [comment]
All good on my end! ty
